### ISSUE TITLE
Joke songs

### ISSUE THREAD

**Issue by rocky-entertainer** [rocky-entertainer/FNF-Mods-and-Crossovers#1]
The Joke songs that I have need to be assigned for the week(s) it will be in.  I would also like to know which songs are going to be used. 
-Thx

**Comment by TabiGg678** [comment]
Yw

**Comment by casielse** [comment]
Do we have the weeks that are going to be put in yet?
@TabiGg678

**Comment by TabiGg678** [comment]
There's gonna be one joke song in the demo for now. But we'll make it as a free play song

**Comment by casielse** [comment]
alright. We could possibly use it in the background during Cut scenes.
