### ISSUE TITLE
Youtube channel link [mine]

### ISSUE THREAD

**Issue by casielse** [rocky-entertainer/FNF-Mods-and-Crossovers#5]
https://www.youtube.com/channel/UC0XAKL_Bb0Rdv0dRG11bjRQ 

also please put me on your yt page under featured.

-Thank you,
Casiel_se

**Comment by TabiGg678** [comment]
K

**Comment by casielse** [comment]
thx

**Comment by casielse** [comment]
I dont see it yet @TabiGg678

**Comment by TabiGg678** [comment]
Cause I'm in school rn

**Comment by casielse** [comment]
same lol
take your time 👍

**Comment by TabiGg678** [comment]
Done
