### ISSUE TITLE
Youtube channel

### ISSUE THREAD

**Issue by casielse** [rocky-entertainer/FNF-Mods-and-Crossovers#6]
I was wondering why I don't see my channel featured on your YT channel

**Comment by TabiGg678** [comment]
It's on there

**Comment by casielse** [comment]
In which section?

**Comment by casielse** [comment]
@TabiGg678 
I am going to make a YT video that you can post on your channel about me. Link will be in maybe 3-5 minutes

**Comment by TabiGg678** [comment]
Okay but I'm in school right now

**Comment by casielse** [comment]
same but its almost done. Take your time when I post it to upload it

**Comment by casielse** [comment]
Can you subscribe to me for videos and also I don't see my channel on there
@TabiGg678

**Comment by TabiGg678** [comment]
![image](https://github.com/rocky-entertainer/FNF-Mods-and-Crossovers/assets/148711965/9339b165-55c8-4a67-a554-f2e356c08238) you're right there and done

**Comment by casielse** [comment]
I see it. Thanks
